name: medusa-backend
region: nyc
services:
  - name: api
    source_dir: /backend
    github:
      repo: your-username/mikdraumida
      branch: main
      deploy_on_push: true
    run_command: npm run start
    build_command: npm run build
    environment_slug: node-js
    instance_size_slug: professional-xs
    instance_count: 1
    http_port: 9000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: COOKIE_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STORE_CORS
        scope: RUN_TIME
      - key: ADMIN_CORS
        scope: RUN_TIME
      - key: AUTH_CORS
        scope: RUN_TIME
